version: '3.8'
services:
  stats-db:
    image: postgres:13-alpine
    container_name: ewm_stats_db
    environment:
      POSTGRES_DB: stats
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "6541:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d stats" ]
      interval: 10s
      timeout: 5s
      retries: 5

  stats-server:
    build: ./stats-server
    container_name: ewm_stats_service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/stats
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "9090:9090"
    depends_on:
      stats-db:
        condition: service_healthy